### ISSUE TITLE
Image for Breakerspace Recap is broken

### ISSUE THREAD

**Issue by bebopkid** [fabricatorzorg/breakerspaces.org#5]
Not sure what I'm doing wrong. Previous photos uploaded fine but this one doesn't display whether it's a jpg or png. 
Pg: https://github.com/fabricatorzorg/breakerspaces.org/blob/master/01recap.md
Img: https://github.com/fabricatorzorg/breakerspaces.org/blob/master/breakerspace01-recap.jpg

**Comment by rejon** [comment]
You are trying to get from the github site, not the deployed site, so:

http://breakerspaces.org/breakerspace01-recap.jpg
